local function slurp(path)
    local f=assert(io.open(path,"r")); local s=f:read("*a"); f:close(); return s
end
local bridge=slurp("safecardbridge.lua")
local list=slurp("alreaderbooklist.lua")
local ui=slurp("libraryui.lua")
assert(bridge:find("adaptiveProfile",1,true), "adaptive profile missing")
assert(bridge:find("libraryx_target_rows",1,true), "target rows not consumed")
assert(bridge:find("local remaining =",1,true), "remaining rows not calculated")
assert(bridge:find("local visible_rows =",1,true), "visible rows not calculated")
assert(bridge:find("available_height / visible_rows",1,true), "short page does not fill viewport")
assert(bridge:find("self.files_per_page = target_rows",1,true), "pagination density is not stable")
assert(bridge:find("truncateCardAuthor",1,true), "dense author line guard missing")
assert(not bridge:find("densityScale",1,true), "legacy density scale still present")
assert(list:find("libraryx_target_rows",1,true), "target rows not propagated")
assert(ui:find("genres = genres",1,true), "genres not supplied separately")
assert(bridge:find("copy.genres = meta.genres",1,true), "genres not overlaid")
print("test_adaptive_cards_static: PASS")
