local function slurp(path)
    local f=assert(io.open(path,'r')); local s=f:read('*a'); f:close(); return s
end
local main=slurp('main.lua')
local list=slurp('alreaderbooklist.lua')
local bridge=slurp('safecardbridge.lua')
local ui=slurp('libraryui.lua')
local details=slurp('libraryxbookdetails.lua')
local i18n=slurp('libraryxi18n.lua')
assert(main:find('libraryxsettingsui',1,true))
assert(main:find('settings',1,true))
assert(list:find('Settings.listDensity()',1,true))
assert(list:find('density_auto',1,true))
assert(bridge:find('Settings.fontScale()',1,true))
assert(bridge:find('math.max(3, math.min(10, derived_rows))',1,true))
assert(bridge:find('Settings.showFileInfo()',1,true))
assert(ui:find('Settings.showGenres()',1,true))
assert(ui:find('Settings.showLanguage()',1,true))
assert(ui:find('Settings.showSeriesIndex()',1,true))
assert(details:find('Settings.detailsBodyScale()',1,true))
assert(details:find('Settings.detailsTitleScale()',1,true))
assert(details:find('Settings.detailsCoverScale()',1,true))
assert(details:find('Settings.detailsShowPath()',1,true))
assert(i18n:find('libraryx_language',1,true))
print('test_settings_integration_static: PASS')
